apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - image: https://ec2-43-202-0-81.ap-northeast-2.compute.amazonaws.com/harbor/projects/2/repositories/flask-example:latest
        name: flask-example
