apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - image: ec2-13-124-102-170.ap-northeast-2.compute.amazonaws.com/fiscicdlab/flask-example:r20231120-010
        name: flask-example

